name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Debug, Release]
        include:
          - os: ubuntu-latest
            cc: gcc
            cxx: g++
          - os: macos-latest
            cc: clang
            cxx: clang++

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup C++ environment
      shell: bash
      run: echo "Setting up C++ build environment"

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential wget

    - name: Build Boost from source (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "Building Boost 1.88.0 from source..."
        cd /tmp
        
        # Download boost 1.88.0
        wget https://archives.boost.io/release/1.88.0/source/boost_1_88_0.tar.gz
        tar -xzf boost_1_88_0.tar.gz
        cd boost_1_88_0
        
        # Configure boost build
        ./bootstrap.sh --with-libraries=thread,system --prefix=$HOME/boost-1.88.0
        
        # Build and install boost
        ./b2 --j$(nproc) variant=release link=shared threading=multi install
        
        echo "Boost build completed. Installation directory: $HOME/boost-1.88.0"
        ls -la $HOME/boost-1.88.0/
        ls -la $HOME/boost-1.88.0/lib/
        ls -la $HOME/boost-1.88.0/include/boost/ | head -10

    - name: Test boost compilation (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "Testing boost compilation with custom build..."
        export BOOST_ROOT=$HOME/boost-1.88.0
        export LD_LIBRARY_PATH=$HOME/boost-1.88.0/lib:$LD_LIBRARY_PATH
        
        echo "=== Test 1: Header-only compilation ==="
        echo '#include <iostream>' > test_headers.cpp
        echo '#include <boost/format.hpp>' >> test_headers.cpp
        echo '#include <boost/random.hpp>' >> test_headers.cpp
        echo 'int main() { std::cout << "Headers OK" << std::endl; return 0; }' >> test_headers.cpp
        g++ -std=c++17 -I$BOOST_ROOT/include test_headers.cpp -o test_headers
        ./test_headers
        echo "✅ Header-only test passed"
        
        echo "=== Test 2: Thread library compilation ==="
        echo '#include <iostream>' > test_thread.cpp
        echo '#include <boost/thread/mutex.hpp>' >> test_thread.cpp
        echo 'int main() { boost::mutex m; std::cout << "Thread OK" << std::endl; return 0; }' >> test_thread.cpp
        g++ -std=c++17 -I$BOOST_ROOT/include test_thread.cpp -L$BOOST_ROOT/lib -lboost_thread -lboost_system -o test_thread
        ./test_thread
        echo "✅ Thread test passed"
        
        echo "=== Test 3: Full boost test ==="
        g++ -std=c++17 -I$BOOST_ROOT/include test_boost.cpp -L$BOOST_ROOT/lib -lboost_thread -lboost_system -o test_boost
        ./test_boost
        echo "✅ Full boost compilation and execution succeeded"

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install cmake boost

    - name: Configure CMake
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          export BOOST_ROOT=$HOME/boost-1.88.0
          export LD_LIBRARY_PATH=$HOME/boost-1.88.0/lib:$LD_LIBRARY_PATH
          cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON \
            -DBoost_ROOT=$BOOST_ROOT \
            -DBoost_INCLUDE_DIR=$BOOST_ROOT/include \
            -DBoost_LIBRARY_DIR=$BOOST_ROOT/lib
        else
          cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON
        fi

    - name: Build
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          export LD_LIBRARY_PATH=$HOME/boost-1.88.0/lib:$LD_LIBRARY_PATH
        fi
        cmake --build build --config ${{ matrix.build_type }} --parallel

    - name: Run Tests
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          export LD_LIBRARY_PATH=$HOME/boost-1.88.0/lib:$LD_LIBRARY_PATH
        fi
        cd build
        ./tests/simple_test
        ./tests/unit_tests
        if [ -f "./tests/performance_tests" ]; then
          echo "Running performance tests..."
          timeout 60 ./tests/performance_tests || echo "Performance tests timed out or failed, continuing..."
        fi

    - name: Run Examples
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          export LD_LIBRARY_PATH=$HOME/boost-1.88.0/lib:$LD_LIBRARY_PATH
        fi
        cd build
        ./examples/basic_example
        ./examples/buffer_operations

  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential cppcheck clang-tidy
        sudo apt-get install -y libboost-dev libboost-thread-dev libboost-system-dev

    - name: Run cppcheck
      run: |
        cppcheck --enable=all --error-exitcode=0 --suppress=missingIncludeSystem \
          --suppress=unusedFunction --suppress=unmatchedSuppression \
          --suppress=noExplicitConstructor --suppress=passedByValue \
          *.cpp *.h examples/*.cpp tests/*.cpp || echo "cppcheck completed with warnings"

    - name: Configure for clang-tidy
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Run clang-tidy
      run: |
        # Create a basic .clang-tidy config if it doesn't exist
        if [ ! -f .clang-tidy ]; then
          echo "Checks: '-*,readability-*,performance-*,modernize-*'" > .clang-tidy
        fi
        clang-tidy -p build \
          Buffer.cpp Random32.cpp Utils.cpp CompareResult.cpp || echo "clang-tidy completed with warnings"

  documentation:
    name: Build Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Generate documentation
      run: |
        doxygen Doxyfile || echo "Doxygen config not found, skipping"

    - name: Upload documentation
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/

  release:
    name: Create Release Artifacts
    runs-on: ubuntu-latest
    needs: [test, code-quality]
    if: github.event_name == 'release'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        sudo apt-get install -y libboost-dev libboost-thread-dev libboost-system-dev

    - name: Build Release
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --parallel

    - name: Package library
      run: |
        cd build
        cpack || echo "CPack not configured"

    - name: Create source archive
      run: |
        git archive --format=tar.gz --prefix=BufferLib-${{ github.ref_name }}/ HEAD > BufferLib-${{ github.ref_name }}-source.tar.gz

    - name: Upload release assets
      uses: actions/upload-artifact@v4
      with:
        name: release-artifacts
        path: |
          BufferLib-*.tar.gz
          build/libbuffer.a 